FROM ubuntu:22.04

RUN apt-get update && apt-get install -y openssh-server python3 sudo
RUN mkdir /var/run/sshd

# Set a password (e.g., 'password') so we can connect
RUN echo 'root:password' | chpasswd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
