FROM ubuntu:22.04

RUN apt-get update && apt-get install -y openssh-server python3 sudo
RUN mkdir /var/run/sshd && mkdir -p /root/.ssh

# Copy your local public key into the slave's authorized_keys
COPY ansible_key.pub /root/.ssh/authorized_keys
RUN chmod 600 /root/.ssh/authorized_keys

RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
